# Generated by Django 5.1.5 on 2025-03-13 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.county')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('school', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('home_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('next_of_kin_address', models.CharField(max_length=255)),
                ('next_of_kin_phone', models.CharField(max_length=15)),
                ('chief_name', models.CharField(max_length=100)),
                ('chief_address', models.CharField(max_length=255)),
                ('chief_phone', models.CharField(max_length=15)),
                ('disability', models.BooleanField(default=False)),
                ('disability_details', models.CharField(blank=True, max_length=255, null=True)),
                ('student_status', models.CharField(choices=[('KUCCPS', 'Government Sponsored (KUCCPS)'), ('PSSP', 'Self Sponsored (PSSP)')], max_length=10)),
                ('residential_status', models.CharField(choices=[('Resident', 'Resident'), ('Non Resident', 'Non Resident')], max_length=15)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.county')),
                ('sub_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subcounty')),
            ],
        ),
    ]
