# Generated by Django 5.1.5 on 2025-03-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parental_status', models.CharField(choices=[('both', 'Have both parents'), ('one', 'Have one parent'), ('orphan', 'Total orphan')], max_length=10)),
                ('death_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('father_age', models.IntegerField(blank=True, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_employer', models.CharField(blank=True, max_length=100, null=True)),
                ('father_health_status', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('mother_age', models.IntegerField(blank=True, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_employer', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_health_status', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('total_siblings', models.IntegerField()),
                ('university_siblings', models.IntegerField(blank=True, null=True)),
                ('secondary_siblings', models.IntegerField(blank=True, null=True)),
                ('out_of_school_siblings', models.IntegerField(blank=True, null=True)),
                ('out_of_school_reason', models.TextField(blank=True, null=True)),
                ('working_siblings_occupation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
