# Generated by Django 5.1.5 on 2025-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_familybackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('school', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('home_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('county', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu')], max_length=20)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('next_of_kin_address', models.CharField(max_length=255)),
                ('next_of_kin_phone', models.CharField(max_length=15)),
                ('chief_name', models.CharField(max_length=100)),
                ('chief_address', models.CharField(max_length=255)),
                ('chief_phone', models.CharField(max_length=15)),
                ('disability', models.BooleanField(default=False)),
                ('disability_details', models.CharField(blank=True, max_length=255, null=True)),
                ('student_status', models.CharField(choices=[('KUCCPS', 'Government Sponsored (KUCCPS)'), ('PSSP', 'Self Sponsored (PSSP)')], max_length=10)),
                ('residential_status', models.CharField(choices=[('Resident', 'Resident'), ('Non Resident', 'Non Resident')], max_length=15)),
                ('parental_status', models.CharField(choices=[('both', 'Have both parents'), ('one', 'Have one parent'), ('orphan', 'Total orphan')], max_length=10)),
                ('death_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('father_age', models.IntegerField(blank=True, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_employer', models.CharField(blank=True, max_length=100, null=True)),
                ('father_health_status', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('mother_age', models.IntegerField(blank=True, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_employer', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_health_status', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('total_siblings', models.IntegerField()),
                ('university_siblings', models.IntegerField(blank=True, null=True)),
                ('secondary_siblings', models.IntegerField(blank=True, null=True)),
                ('out_of_school_siblings', models.IntegerField(blank=True, null=True)),
                ('out_of_school_reason', models.TextField(blank=True, null=True)),
                ('working_siblings_occupation', models.TextField(blank=True, null=True)),
                ('school_fee_payer', models.CharField(max_length=255)),
                ('school_fee_evidence', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('work_study', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('work_study_evidence', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('external_support', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('sponsor_source', models.CharField(blank=True, choices=[('HELB', 'HELB'), ('NGO', 'NGO'), ('CDF', 'CDF'), ('Other', 'Other')], max_length=50, null=True)),
                ('sponsor_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuition_fee_paid', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('fee_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_statement', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('deferred_study', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('defer_reason', models.CharField(blank=True, choices=[('Medical', 'Medical'), ('Social', 'Social'), ('Financial', 'Financial'), ('Academic', 'Academic')], max_length=50, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('additional_info_evidence', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='county',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='county',
        ),
        migrations.DeleteModel(
            name='FamilyBackground',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='sub_county',
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
        migrations.DeleteModel(
            name='SubCounty',
        ),
    ]
