# Generated by Django 5.1.5 on 2025-03-18 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentapplication_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='academic_year',
            field=models.CharField(default='2024/2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='county',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kericho', 'Kericho'), ('Nakuru', 'Nakuru'), ('Kakamega', 'Kakamega'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nandi', 'Nandi'), ('Bomet', 'Bomet'), ('Narok', 'Narok'), ('Bungoma', 'Bungoma')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='father_employer',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Not employed', 'Not employed')], default='Employed', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='mother_employer',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Not employed', 'Not employed')], default='Employed', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='school',
            field=models.CharField(choices=[('SCI', 'SCI'), ('SEDU', 'SEDU'), ('SDHMA', 'SDHMA'), ('SOM', 'SOM'), ('SEBE', 'SEBE'), ('SASS', 'SASS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='school_fee_payer',
            field=models.CharField(choices=[('Parent', 'Parent'), ('External Sponsor', 'External Sponsor')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='studentapplication',
            unique_together={('student', 'academic_year')},
        ),
    ]
