# Generated by Django 5.1.5 on 2025-03-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAllocationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('total_funds', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='academic_year',
            field=models.CharField(default='2024/2025', max_length=9),
        ),
    ]
